name: Build and Publish PDFs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up LaTeX environment
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full texlive-latex-extra texlive-fonts-recommended texlive-bibtex-extra biber make

      # Step 3: Check if required files exist
      - name: Check LaTeX source files
        run: |
          ls -R  # Mostra tutti i file presenti (utile per debug)
          if [ ! -f "overleaf.tex" ]; then echo "❌ ERRORE: overleaf.tex non trovato!"; exit 1; fi
          if [ ! -d "setup" ]; then echo "⚠️ ATTENZIONE: Cartella setup/ non trovata!"; fi
          if [ ! -d "chapters" ]; then echo "⚠️ ATTENZIONE: Cartella chapters/ non trovata!"; fi

      # Step 4: Compile overleaf.pdf (cattura errori LaTeX)
      - name: Compile overleaf.pdf
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error overleaf.tex || (echo "❌ ERRORE LaTeX: Guarda il log sopra" && exit 1)
          bibtex overleaf || echo "⚠️ BibTeX fallito, ma continuo..."
          pdflatex -interaction=nonstopmode -halt-on-error overleaf.tex
          pdflatex -interaction=nonstopmode -halt-on-error overleaf.tex

      # Step 5: Create output directory and move PDFs
      - name: Prepare PDFs for deployment
        run: |
          mkdir -p output
          if [ -f "overleaf.pdf" ]; then mv overleaf.pdf output/; else echo "❌ ERRORE: overleaf.pdf non trovato!"; exit 1; fi

      # Step 6: Deploy to PDF branch
      - name: Deploy to PDF branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf
          publish_dir: output
          force_orphan: true
          keep_files: false
          commit_message: "Update overleaf.pdf"
